import os
import sys
import shutil
import time

def _get_apo_template_dir():
    if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
        return os.path.join(sys._MEIPASS, "apo")
    return os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "apo")

# Maps app-internal speaker names → Equalizer APO channel identifiers
APO_CHANNEL_MAP = {
    "towerL":    "L",
    "towerR":    "R",
    "center":    "C",
    "subwoofer": "LFE",
    "surroundL": "RL",
    "surroundR": "RR",
}

# Path to the production APO config folder
APO_CONFIG_DIR = r"C:\Program Files\EqualizerAPO\config"


def set_apo_include_state(filename, enabled):
    """Enables/disables inclusion of a specific config file in Equalizer APO's config.txt."""
    config_path = os.path.join(APO_CONFIG_DIR, "config.txt")
    if not os.path.exists(config_path):
        return False
        
    max_retries = 5
    delay = 0.1
    
    for attempt in range(max_retries):
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                lines = f.readlines()
            
            modified = False
            new_lines = []
            for line in lines:
                if filename in line and "Include" in line:
                    clean_line = line.replace("#", "").strip()
                    if enabled:
                        new_lines.append(clean_line + "\n")
                    else:
                        new_lines.append("# " + clean_line + "\n")
                    modified = True
                else:
                    new_lines.append(line)
            
            if not modified:
                line_to_add = f"Include: {filename}\n" if enabled else f"# Include: {filename}\n"
                new_lines.append(line_to_add)
                
            with open(config_path, "w", encoding="utf-8") as f:
                f.writelines(new_lines)
            return True
        except PermissionError as pe:
            if attempt < max_retries - 1:
                time.sleep(delay)
                continue
            print(f"[set_apo_include_state] Permission denied (attempt {attempt+1}/{max_retries}): {pe}")
            return False
        except Exception as e:
            print(f"[set_apo_include_state] Error: {e}")
            return False
    return False


def set_bass_management_state(enabled):
    """Enables/disables the Equalizer APO crossover/bass management file inclusion."""
    return set_apo_include_state("BassManagement.txt", enabled)


def write_calibration_delay_file(delays, gains=None):
    """
    Write (or overwrite) the production RoomCalibration.txt with per-channel
    delay and gain preamp directives.
    """
    prod_path = os.path.join(APO_CONFIG_DIR, "RoomCalibration.txt")

    # Relative-delay fix: subtract the minimum so the nearest speaker = 0ms
    if delays:
        min_raw = min(delays.values())
        norm_delays = {k: max(0, v - min_raw) for k, v in delays.items()}
    else:
        norm_delays = {}

    lines = [
        "# =====================================================================\n",
        "# Per-Channel Phase Delay and Gain Preamp Calibration\n",
        "# Auto-generated by Samsung Audioscape Controller\n",
        "# Closest speaker = 0.0 ms; Gain normalized to prevent clipping.\n",
        "# =====================================================================\n",
        "\n",
    ]

    for name, raw_val in norm_delays.items():
        apo_channel = APO_CHANNEL_MAP.get(name)
        if apo_channel is None:
            continue
        ms_value = raw_val / 10.0
        lines.append(f"Channel: {apo_channel}\n")
        lines.append(f"Delay: {ms_value:.1f} ms\n")
        if gains and name in gains:
            lines.append(f"Preamp: {gains[name]:.1f} dB\n")

    # If no delays provided, write 0ms defaults for all channels
    if not lines or len(lines) <= 6:
        for apo_channel in ["L", "R", "C", "SUB", "SL", "SR"]:
            lines.append(f"Channel: {apo_channel}\n")
            lines.append(f"Delay: 0.0 ms\n")
            lines.append(f"Preamp: 0.0 dB\n")

    try:
        os.makedirs(APO_CONFIG_DIR, exist_ok=True)
        with open(prod_path, "w", encoding="utf-8") as f:
            f.writelines(lines)
        return True
    except Exception as e:
        print(f"[RoomCalibration] Failed to write delay file: {e}")
        return False


def set_room_calibration_state(enabled):
    """
    Enable or disable Room Calibration and its dedicated upmix file in the APO config.
    When enabling, ensures both RoomCalibration.txt and UpmixForRoomCalibration.txt
    are written to the production APO directory and active.
    """
    # Note: relative path calculation changed because we are inside the services/ subdirectory
    local_upmix_template = os.path.normpath(os.path.join(
        _get_apo_template_dir(), "UpmixForRoomCalibration.txt"
    ))
    prod_upmix_path = os.path.join(APO_CONFIG_DIR, "UpmixForRoomCalibration.txt")
    prod_cal_path = os.path.join(APO_CONFIG_DIR, "RoomCalibration.txt")

    if enabled:
        # 1. Deploy the static upmix configuration file to production APO directory
        try:
            os.makedirs(APO_CONFIG_DIR, exist_ok=True)
            if os.path.exists(local_upmix_template):
                shutil.copy2(local_upmix_template, prod_upmix_path)
            else:
                # Fallback static generation if local template is missing
                fallback_content = (
                    "Preamp: -4.0 dB\n\n"
                    "If: inputChannelCount == 2\n"
                    "    Copy: L=L R=R C=L RL=L RR=R LFE=L+R\n"
                    "    Channel: LFE\n"
                    "    Filter: ON LPQ Fc 120 Hz Q 0.707\n"
                    "EndIf:\n"
                )
                with open(prod_upmix_path, "w", encoding="utf-8") as f:
                    f.write(fallback_content)
        except Exception as e:
            print(f"[RoomCalibration] Failed to copy static upmix template: {e}")

        # 2. Ensure calibration delay and gain file exists with current values
        import config_manager
        delays = config_manager.get("calibration_delays", {})
        gains = config_manager.get("calibration_gains", {})
        write_calibration_delay_file(delays, gains=gains)

        # 3. Include both files in config.txt
        ok_upmix = set_apo_include_state("UpmixForRoomCalibration.txt", True)
        ok_cal = set_apo_include_state("RoomCalibration.txt", True)
        return ok_upmix and ok_cal
    else:
        # Comments out both files from config.txt
        ok_upmix = set_apo_include_state("UpmixForRoomCalibration.txt", False)
        ok_cal = set_apo_include_state("RoomCalibration.txt", False)
        return ok_upmix and ok_cal


def set_preset_state(preset_name, enabled):
    """Enables or disables the Equalizer APO preset file inclusion."""
    filename_map = {
        "bassboosted": "BassBoostedPreset.txt",
        "tightbass": "TightBassPreset.txt",
        "hallvibe": "HallVibePreset.txt",
        "echo": "EchoPreset.txt",
        "upmixing": "upmixer.txt"
    }
    filename = filename_map.get(preset_name)
    if not filename:
        return False

    prod_path = os.path.join(APO_CONFIG_DIR, filename)
    if enabled and not os.path.exists(prod_path):
        try:
            local_preset_path = os.path.join(_get_apo_template_dir(), filename)
            if os.path.exists(local_preset_path):
                shutil.copy2(local_preset_path, prod_path)
            else:
                print(f"[set_preset_state] Local preset template not found at {local_preset_path}")
                return False
        except Exception as e:
            print(f"[set_preset_state] Failed to copy preset template: {e}")
            return False

    return set_apo_include_state(filename, enabled)
